#!/bin/sh

# remove bin if it exists and remake the directory
rm -r bin
mkdir bin
# move into source and build
cd src

if [ "$1" == "debug" ]; then
	./build debug
else
	./build
fi

# move executable out of src to bin
mv main ../bin/
